### ISSUE TITLE
Upgrading to Swift 3

### ISSUE THREAD

**Issue by lindseyvastola** [cwliu/linphone-swift-demo#1]
This repository doesn't upgrade nicely. Have you thought about updating the code to Swift 3?

**Comment by cwliu** [comment]
PR2 has address this issue https://github.com/cwliu/linphone-swift-demo/pull/2 
Please take a look. Does this PR fit your case? Thanks.

**Comment by lindseyvastola** [comment]
Thank you fro the update. There is an error though. It catches in makecall on the code before if you make a call after it sits for a bit or make multiple calls in a row 
  guard let _ = setIdentify() else {
            print("no identity")
            return;
        }

**Comment by Rain-dew** [comment]
您好，我猜测您应该是能看懂中文的。
我运行了您的demo，发现没有任何UI。我更改了个人账户、服务器，但是运行后一直打印keep alive send to...我有些疑惑这样子是做到什么效果呢？我希望实现一个视频聊天和语音聊天。若您有时间可加入部分简单UI吗？

**Comment by cwliu** [comment]
@Rain-dew 建議你可以改一個新的 issue 來描述你的問題喔。

BTW 建議可以直接從 

```
    func demo() {
//        makeCall()
//        autoPickImcomingCall()
        idle()
    }

```

這個 function 開始 trace.
