### ISSUE TITLE
Listen to registration_state_changed

### ISSUE THREAD

**Issue by sree127** [cwliu/linphone-swift-demo#3]
Hi @cwliu  @eliburke  

Thanks for the awesome sample for Swift. I was wondering if there was any to listen to **registration_state_changed**? 

```
let registrationStateChanged: LinphoneCoreRegistrationStateChangedCb  = {
    (lc: Optional<OpaquePointer>, proxyConfig: Optional<OpaquePointer>, state: _LinphoneRegistrationState, message: Optional<UnsafePointer<Int8>>) in

    switch state{
    case LinphoneRegistrationNone: /**<Initial state for registrations */
        NSLog("LinphoneRegistrationNone")

    case LinphoneRegistrationProgress:
        NSLog("LinphoneRegistrationProgress")

    case LinphoneRegistrationOk:
        NSLog("LinphoneRegistrationOk")

    case LinphoneRegistrationCleared:
        NSLog("LinphoneRegistrationCleared")

    case LinphoneRegistrationFailed:
        NSLog("LinphoneRegistrationFailed")

    default:
        NSLog("Unkown registration state")
    }
}
```

From the above call back I'd like to call another method to carry out other operations. I tried calling a method & I got **a C function pointer cannot be formed from a closure that captures context**. Also I tried the below method but it threw the same error. 

`let classObject = UnsafeMutableRawPointer(Unmanaged.passRetained(self).toOpaque())
`
And from inside the registrationStateChanged closure : 

`let some =  Unmanaged<LinphoneManager>.fromOpaque(classObject).takeUnretainedValue()
`

Can you please help me out with this one? Thanks a lot

**Comment by eliburke** [comment]
@sree127 I haven't had a chance to do additional Linphone development in Swift, but I suspect the answer is the same as for Objective C-- turn the callbacks and the C data types into notifications carrying Swift data types. The callback is only there to be a translation layer.
Example: (in ObjC, but the intent should be clear even if you don't know the language)

```
- (void)onRegister:(LinphoneCore *)lc cfg:(LinphoneProxyConfig*) cfg state:(LinphoneRegistrationState) state message:(const char*) message {
    LinphoneReason reason = linphone_proxy_config_get_error(cfg);
    NSMutableDictionary* dict = [NSMutableDictionary dictionary];
    [dict setObject:[NSNumber numberWithInt:state] forKey:@"state"];
    [dict setObject:[NSNumber numberWithInt:reason] forKey:@"reason"];
    if (message)
        [dict setObject:[NSString stringWithUTF8String:message] forKey:@"message"];

    [[NSNotificationCenter defaultCenter] postNotificationName:kLinphoneRegistrationUpdate object:self userInfo:dict];
}
```

**Comment by sree127** [comment]
Hey @eliburke, thanks. I used `NotificationCenter` to pass the data. Thanks a lot.
