### ISSUE TITLE
App freezes after launch

### ISSUE THREAD

**Issue by myklll** [cwliu/linphone-swift-demo#6]
I edited the Secret.plist file with new and correct credentials, but the app freezes upon launch.

Thanks

**Comment by cwliu** [comment]
Hi @mychell, this demo doesn't has any UI on it.  It's CLI demo only.

**Comment by cwliu** [comment]
I modified the code flow to be in an asynchronous way, and it fixed in  https://github.com/cwliu/linphone-swift-demo/commit/fcd18e99bb46257cdb0dc4cc28ffa613d8ae7900
